version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: electron
    versions:
    - 11.2.3
    - 11.3.0
    - 12.0.0
    - 12.0.1
    - 12.0.2
    - 12.0.4
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.22.0
    - 7.23.0
  - dependency-name: adm-zip
    versions:
    - 0.5.4
  - dependency-name: ejs
    versions:
    - 3.1.6
